chore: require protobuf>=3.20.0
To avoid this error:

```
Traceback (most recent call last): File "<frozen runpy>", line 189, in _run_module_as_main File "<frozen runpy>", line 112, in _get_module_details File "/generation_service/.venv/lib/python3.11/site-packages/isolate/server/__init__.py", line 1, in <module> from isolate.server.server import BridgeManager, IsolateServicer # noqa: F401 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/generation_service/.venv/lib/python3.11/site-packages/isolate/server/server.py", line 30, in <module> from isolate.connections.grpc import AgentError, LocalPythonGRPC File "/generation_service/.venv/lib/python3.11/site-packages/isolate/connections/grpc/__init__.py", line 1, in <module> from isolate.connections.grpc._base import AgentError, LocalPythonGRPC # noqa: F401 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/generation_service/.venv/lib/python3.11/site-packages/isolate/connections/grpc/_base.py", line 16, in <module> from isolate.connections.grpc import agent, definitions File "/generation_service/.venv/lib/python3.11/site-packages/isolate/connections/grpc/agent.py", line 35, in <module> from isolate.connections.grpc import definitions File "/generation_service/.venv/lib/python3.11/site-packages/isolate/connections/grpc/definitions/__init__.py", line 3, in <module> from isolate.connections.grpc.definitions.agent_pb2 import * # noqa: F403 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/generation_service/.venv/lib/python3.11/site-packages/isolate/connections/grpc/definitions/agent_pb2.py", line 9, in <module> from google.protobuf.internal import builder as _builder ImportError: cannot import name 'builder' from 'google.protobuf.internal' (/generation_service/.venv/lib/python3.11/site-packages/google/protobuf/internal/__init__.py)
```